# Generated by Django 3.1.2 on 2020-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanWebApp', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
